# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_id', models.UUIDField(default=uuid.uuid4)),
                ('num_players', models.IntegerField()),
                ('has_started', models.BooleanField(default=False)),
                ('game_state', models.CharField(choices=[('starting', 'Starting'), ('pick_wc', 'Waiting for Players To Pick White Cards'), ('pick_win', 'Pick Winner'), ('game_over', 'Game Over')], default='starting', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=60)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cah.Game')),
                ('hand', models.ManyToManyField(to='cah.Card')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='card_czar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_card_czar_game', to='cah.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_black_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_current_black_card_games', to='cah.Card'),
        ),
        migrations.AddField(
            model_name='game',
            name='decks',
            field=models.ManyToManyField(to='cah.Deck'),
        ),
        migrations.AddField(
            model_name='game',
            name='discarded',
            field=models.ManyToManyField(to='cah.Card'),
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_game_host', to='cah.Player'),
        ),
    ]
