# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 07:27
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0003_auto_20161218_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
