# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0007_auto_20161218_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', positions.fields.PositionField(default=-1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cah.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='playergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cah.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='cah.PlayerGame', to='cah.Player'),
        ),
    ]
