# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0008_auto_20161218_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='card_czar',
        ),
        migrations.RemoveField(
            model_name='game',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.RemoveField(
            model_name='game',
            name='num_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
