# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0010_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_czar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_card_czar_game', to='cah.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='decks',
            field=models.ManyToManyField(to='cah.Deck'),
        ),
    ]
