# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0011_auto_20161218_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_game_host', to='cah.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
