# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0014_auto_20161218_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win_points',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=3),
        ),
    ]
