# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0015_auto_20161218_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_round_winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='_game_last_round_winner', to='cah.Player'),
            preserve_default=False,
        ),
    ]
