# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0016_game_last_round_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_round_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_game_last_round_winner', to='cah.Player'),
        ),
    ]
