# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0017_auto_20161218_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='awesome_points',
            field=models.IntegerField(default=0),
        ),
    ]
