# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0012_auto_20161218_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='playergame',
            name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cah.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
        migrations.DeleteModel(
            name='PlayerGame',
        ),
    ]
