# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0013_auto_20161218_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cah.Game'),
        ),
    ]
